name:                firelink
version:             0.0.2.0
github:              "aitorres/firelink"
license:             BSD3
author:              "Andrés Ignacio Torres, Germán Robayo"
maintainer:          "example@example.com"
copyright:           "2019 (c) Andrés Ignacio Torres, Germán Robayo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aitorres/firelink#readme>

dependencies:
- base >= 4.7 && < 5
- array
- split
- extra

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
    - hlint

executables:
  firelink-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firelink

tests:
  lexer-tests:
    main:                Spec.hs
    source-dirs:         test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firelink
    - hspec
    - hspec-discover
